server.port=8391
request.path=/api

sqlconn = 
log.dir=./logs/

redis.addr =
redis.password =

wechat.appid =
wechat.secret =

oss.enabled = false
oss.dirPrefix = dev
oss.endpoint =
oss.bucketName =
oss.accessKeyId =
oss.accessKeySecret =
oss.expireTime = 600
oss.callbackUrl =
oss.tokenExpireTime = 300

ocr.endpoint = https://ocr-api.cn-hangzhou.aliyuncs.com
ocr.accessKeyId =
ocr.accessKeySecret =
ocr.timeoutSeconds = 15
ocr.ossUrlExpireSeconds = 600
ocr.idCard.outputFigure = false
ocr.idCard.outputQualityInfo = false
