server.port=8391

request.path=/

sqlconn = sn:shennongA4622511z3!@tcp(rm-bp11qx2byv7h5is0gio.mysql.rds.aliyuncs.com:3306)/shennong?charset=utf8&parseTime=True&loc=Local

log.dir=./logs/

redis.addr = r-bp1ay4uljr03onj3dppd.redis.rds.aliyuncs.com:6379

redis.password = 83)(QI%k_5t=gJ*L(w&Xu)_$2=oGD=Vf

wechat.appid =wxd2650f0192548f08
wechat.secret =9f87a3e5cc9262b58a1f0469babaddea

grain.farmer.crypto.key = shennong-grain-farmer-field-key-2026

oss.enabled = true

oss.dirPrefix = sku

oss.endpoint = oss-cn-hangzhou.aliyuncs.com

oss.bucketName = sn-2026
ocr.accessKeyId =LTAI5t61ETQgdAfcaqtpiT9b

ocr.accessKeySecret =hXCULms79ggnZDh0cMoye3kT4Y1RwS
oss.expireTime = 600


oss.callbackUrl =

oss.tokenExpireTime = 300

ocr.endpoint = https://ocr-api.cn-hangzhou.aliyuncs.com

ocr.accessKeyId =LTAI5t61ETQgdAfcaqtpiT9b

ocr.accessKeySecret =hXCULms79ggnZDh0cMoye3kT4Y1RwS

ocr.timeoutSeconds = 15

ocr.ossUrlExpireSeconds = 600

ocr.idCard.outputFigure = false

ocr.idCard.outputQualityInfo = false
