server.port=8391
request.path=/api

sqlconn = 
log.dir=./logs/

redis.addr =
redis.password =

wechat.appid =
wechat.secret =

oss.enabled = false
oss.dirPrefix = dev
oss.endpoint =
oss.bucketName =
oss.accessKeyId =
oss.accessKeySecret =
oss.expireTime = 600
oss.callbackUrl =
oss.tokenExpireTime = 300
